<a href="https://colab.research.google.com/github/jon890613/AI_and_security_2020/blob/master/1007.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
ar2=np.array([[1,3,5],[2,8,7]]) #
# ar2.shape
ar2.ndim  #維度

2

In [10]:
ar=np.array([2,4,6,8]); 
ar.dtype

dtype('int64')

In [17]:
f_ar = np.array([13,-3,8.88])
print(f_ar)

intf_ar=f_ar.astype(int)
print(intf_ar)

[13.   -3.    8.88]
[13 -3  8]


In [20]:
data = np.random.randn(2,3)
print(data)

[[-0.76505306 -0.43454336  0.14432207]
 [ 0.45647399  0.1271756  -0.54305463]]


In [27]:
data = np.random.uniform(1,5,5)
print(data)

[4.90609656 3.58347658 1.37179701 3.87114029 1.34274464]


In [28]:
sum(data)

15.075255069891961